language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
install:
    - pip install -r requirements.txt
    - pip install ./
script:
    - pep8 pycc/
    - pyflakes pycc/
    - py.test tests/
